added ingress

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -83,13 +83,27 @@ jobs:
         run: |
           kubectl get nodes
       
-      - name: Uninstall ALB Ingress Controller
-        run: |
-          helm uninstall aws-load-balancer-controller -n kube-system || echo "Helm release not found"
-          kubectl delete crd targetgroupbindings.elbv2.k8s.aws || echo "CRD not found"
-          kubectl delete serviceaccount aws-load-balancer-controller -n kube-system || echo "Service account not found"
-          echo $(aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_REGION --query "cluster.resourcesVpcConfig.vpcId" --output text)
+#      - name: Uninstall ALB Ingress Controller
+#        run: |
+#          helm uninstall aws-load-balancer-controller -n kube-system || echo "Helm release not found"
+#          kubectl delete crd targetgroupbindings.elbv2.k8s.aws || echo "CRD not found"
+#          kubectl delete serviceaccount aws-load-balancer-controller -n kube-system || echo "Service account not found"
+#          echo $(aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_REGION --query "cluster.resourcesVpcConfig.vpcId" --output text)
 #          kubectl delete ingress --all -n default || echo "No ingress resources found"
+      
+      - name: Install AWS Load Balancer Controller
+        run: |
+          helm repo add eks https://aws.github.io/eks-charts
+          helm repo update
+          kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
+          helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
+            --set clusterName=test-eks \
+            --set serviceAccount.create=false \
+            --set serviceAccount.name=aws-load-balancer-controller \
+            --set region=us-east-1 \
+            --set vpcId=$(aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_REGION --query "cluster.resourcesVpcConfig.vpcId" --output text) \
+            --namespace kube-system
+
           
 
 #      - name: Deployment + Service + Ingress
